### ISSUE TITLE
Ability to clear all the current tasks on queue

### ISSUE THREAD

**Issue by gustavoFreireS** [energizer91/smart-request-balancer#13]
there are some cases when the developer wants to clear the request queue for example:
if you want to have a polling executing every 5 seconds with low priority but when the condition for this polling to stop is fulfilled you do not want to make the remaining requests stored on the queue

this could be solved adding a public function to clear the array Map, something like:

```
public clear() {
    debug('Clearing queue', key);
    this.queue.clear();
  }
```

**Comment by energizer91** [comment]
Hi @gustavoFreireS! This sounds like a good api extension. The pull request is on it's way

**Comment by energizer91** [comment]
Done. This feature is now in v2.1.0
