### ISSUE TITLE
request returns undefined

### ISSUE THREAD

**Issue by PlkMarudny** [energizer91/smart-request-balancer#23]
This should return a promise with the result (of what exactly?)

`request(handler: (retry: RetryFunction) => Promise, key: string, rule: string) => Promise`

I get `undefined` always, in the `.then(result => console.log(results)` block.

**Comment by energizer91** [comment]
Hi @PlkMarudny ! That's not the expected behavior. Could you please provide a code snippet of how you use this method?

**Comment by PlkMarudny** [comment]
Hi, it was 3 years ago...

**Comment by energizer91** [comment]
No worries! I agree, this reply was quite late, sorry for missing it. Closing.
